# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: staging
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"
