---
jupyter:
  description: Jupyter Settings and tokens
  type: "object"
  required: true
  properties:
    dev_token:
      type: "string"
      description: "Token for test.jupyter.stfc.ac.uk"
      required: false
    training_token:
      type: "string"
      description: "Token for training.jupyter.stfc.ac.uk"
      required: false
    prod_token:
      type: "string"
      description: "Token for jupyter.stfc.ac.uk"
      required: false

smtp_accounts:
  description: "SMTP accounts"
  type: "array"
  required: true
  items:
    type: "object"
    required: true
    properties:
      name:
        description: "Name of the account"
        type: "string"
        secret: false
        required: true
      server:
        description: "Email server name - e.g. imap.gmail.com"
        type: "string"
        secret: false
        required: true
      username:
        description: "Mailbox username"
        type: "string"
        required: false
      password:
        description: "Mailbox password."
        type: "string"
        secret: true
        required: false
      port:
        description: "Port to connect to - e.g. 465, 587."
        type: "integer"
        default: 465
        required: true
      secure:
        description: "Set to False to disable secure protocol. Default value is True."
        type: "boolean"
        default: true
      smtp_auth:
        description: "Authenticate username and password with SMTP server to send email. Default True"
        type: "boolean"
        default: true
max_attachment_size:
  description: "Maxium size of downloaded attachment in bytes (default 1024)"
  type: "integer"
  required: false
  default: 1024
attachment_datastore_ttl:
  description: "TTL in seconds to keep attachments in the datastore. Default 1800"
  type: "integer"
  required: false
  default: 1800

jira_accounts:
  type: "array"
  required: true
  description: Jira Settings and tokens
  items:
    type: "object"
    required: true
    properties:
      name:
        description: "Name of the jira account"
        type: "string"
        secret: false
        required: true
      username:
        type: "string"
        description: "Username for stfc.atlassian.net"
        required: true
      api_token:
        type: "string"
        description: "Token for stfc.atlassian.net"
        required: true
        secret: true
      atlassian_endpoint:
        type: "string"
        description: "atlassian endpoint"
        required: true
        secret: false
        default: "https://stfc.atlassian.net"

icinga_accounts:
  type: "array"
  required: true
  description: Icinga account
  items:
    type: "object"
    required: true
    properties:
      name:
        description: "Name of the jira account"
        type: "string"
        secret: false
        required: true
      username:
        type: "string"
        description: "Username for icinga"
        required: true
      password:
        type: "string"
        description: "Password for icinga"
        required: true
        secret: true
      icinga_endpoint:
        type: "string"
        description: "icinga endpoint"
        required: true
        secret: false
        default: ""

alertmanager_accounts:
  type: "array"
  required: true
  description: Alertmanager account
  items:
    type: "object"
    required: true
    properties:
      name:
        description: "Name of the alertmanager account"
        type: "string"
        secret: false
        required: true
      username:
        type: "string"
        description: "Username for alertmanager"
        required: true
      password:
        type: "string"
        description: "Password for alertmanager"
        required: true
        secret: true
      alertmanager_endpoint:
        type: "string"
        description: "alertmanager endpoint"
        required: true
        secret: false
        default: ""

sensor_cloud_account:
  description: Which cloud account sensors requiring an openstack connection will use
  type: "string"
  required: true
  default: "dev"
  enum:
    - dev
    - prod

sensor_source_cloud:
  description: The source cloud from which the sensor will apply updates
  type: "string"
  required: true
  default: "prod"
  enum:
    - dev
    - prod

sensor_dest_cloud:
  description: The destination cloud which the sensor will apply any required updates to
  type: "string"
  required: true
  default: "dev"
  enum:
    - dev
    - prod

router_sensor:
  description: "Openstack Router sensor specific settings."
  type: "object"
  required: false
  additionalProperties: false
  properties:
    cloud_account:
      type: "string"
      description: "cloud account to use - set in clouds.ymal"
      default: "dev"
      required: true

hypervisor_sensor:
  description: "Hypervisor sensor specific settings."
  type: "object"
  required: false
  additionalProperties: false
  properties:
    uptime_limit:
      type: "number"
      description: "Number of uptime days before marking hypervisor for maintenance"
    state_expire_after:
      type: "integer"
      description: "Number of seconds before forcefully deleting previous state to update hypervisors stuck in a state"

flavor_sensor:
  description: "Flavor sensor specific settings."
  type: "object"
  required: false
  additionalProperties: false

chatops_sensor:
  description: "ChatOps sensor specific settings."
  type: "object"
  required: false
  additionalProperties: false
  properties:
    endpoint:
      type: "string"
      description: "ChatOps endpoint to use."
    token:
      type: "string"
      description: "API token to authenticate requests."
      secret: true
    channel:
      type: "string"
      description: "Channel to send reminders to."

image_sensor:
  description: "Image sensor specific settings."
  type: "object"
  required: false
  additionalProperties: false

host_aggregate_sensor:
  description: "Host aggregate sensor specific settings."
  type: "object"
  required: false
  additionalProperties: false
