---
jupyter:
  description: Jupyter Settings and tokens
  type: "object"
  required: true
  properties:
    dev_token:
      type: "string"
      description: "Token for test.jupyter.stfc.ac.uk"
      required: false
    training_token:
      type: "string"
      description: "Token for training.jupyter.stfc.ac.uk"
      required: false
    prod_token:
      type: "string"
      description: "Token for jupyter.stfc.ac.uk"
      required: false

cloud_names:
  description: "Cloud name to use in automated jobs"
  type: "object"
  required: true
  properties:
    dev_cloud:
      type: "string"
      description: "Cloud to use when running Automated Jobs on Dev"
      required: false
    prod_cloud:
      type: "string"
      description: "Cloud to use when running Automated Jobs on Prod"
      required: false
    selected_env:
      type: "string"
      description: "Environment stackstorm running in"
      required: true


smtp_accounts:
  description: "SMTP accounts"
  type: "array"
  required: true
  items:
    type: "object"
    required: true
    properties:
      name:
        description: "Name of the account"
        type: "string"
        secret: false
        required: true
      server:
        description: "Email server name - e.g. imap.gmail.com"
        type: "string"
        secret: false
        required: true
      username:
        description: "Mailbox username"
        type: "string"
        required: false
      password:
        description: "Mailbox password."
        type: "string"
        secret: true
        required: false
      port:
        description: "Port to connect to - e.g. 465, 587."
        type: "integer"
        default: 465
        required: true
      secure:
        description: "Set to False to disable secure protocol. Default value is True."
        type: "boolean"
        default: true
      smtp_auth:
        description: "Authenticate username and password with SMTP server to send email. Default True"
        type: "boolean"
        default: true
max_attachment_size:
  description: "Maxium size of downloaded attachment in bytes (default 1024)"
  type: "integer"
  required: false
  default: 1024
attachment_datastore_ttl:
  description: "TTL in seconds to keep attachments in the datastore. Default 1800"
  type: "integer"
  required: false
  default: 1800
