from typing import Optional, List
import logging
import re
import requests
from apis.wazuh_api.structs.wazuh_account import WazuhAccount

logger = logging.getLogger(__name__)


def _query_agents(
    wazuh_token: str,
    endpoint: str,
    values: Optional[List] = None,
    query: Optional[str] = None,
) -> List:
    """
    Queries all agents in Wazuh to get a certain list of parameters
    for a specific query or filter

    :param wazuh_token: wazuh token to make API call with
    :param endpoint: Wazuh endpoint to query
    :param values: the list of variables to retrieve
    :type values: list
    :param query: the specific query against the Wazuh server
    :type query: str
    :return: the information in Wazuh for all agents
    :rtype: list
    """
    logger.info("Querying all agents for values %s and query %s", values, query)
    url = f"{endpoint}/agents"
    headers = {
        "Authorization": f"Bearer {wazuh_token}",
        "Content-Type": "application/json",
    }
    # we query Wazuh using pagination
    # we do not know how many agents there are
    out = []
    params = {
        "limit": 500,
        "offset": 0,
        "select": values,
        "q": query,
    }
    while True:
        try:
            response = requests.get(
                url, headers=headers, params=params, verify=False, timeout=60
            )
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            raise RuntimeError("Failed to fetch data for all agents") from e
        data = response.json()
        items = data.get("data", {}).get("affected_items", [])
        # finished pagination loop
        if not items:
            break
        out.extend(items)
        # restart pagination loop with new offset
        params["offset"] += params["limit"]
    logger.info("Data for all agents fetched correctly")
    return out


def wazuh_list_servers_by_os(
    wazuh_account: WazuhAccount, os_name: str, os_version: str
):
    """
    query the Wazuh server to get data only for
    VMs running a specific version of the OS

    :param os_name: the OS name
    :type os_name: str
    :param os_version: the OS version
    :type os_version: str
    :return: the list of VM IDs
    :rtype: list
    """
    wazuh_token = wazuh_account.get_wazuh_token()
    logger.info(
        "query Wazuh for Servers running OS name %s and %s version",
        os_name,
        os_version,
    )
    query = f"os.platform={os_name};os.major={os_version};status=active;group!=kolla"
    # we ensure we only get information about Servers and not Hypervisors
    # by adding conditions
    #   group!=kolla
    # to the query string
    data = _query_agents(
        wazuh_token, wazuh_account.wazuh_endpoint, values=["name"], query=query
    )

    # extract the Server ID from the fetched data
    #
    # the variable "name" for OpenStack Servers looks like this:
    #   host-192-168-231-139.openstacklocal-001682d2-79a2-41b9-af7f-c553f7d67b0d
    # this Agent name has been generated by this snippet 
    #   https://github.com/stfc/cloud-image-builders/blob/710988483da6c65cb812041693b2348dc7c2c40f/os_builders/roles/vm_baseline/files/wazuh/enrich-wazuh-agent.py#L69-L76
    # which generates the Agent name as
    #   agent_hostname = agent_hostname + "-" + openstack_metadata["uuid"]
    # we need to extract the ID from there
    #
    # An alternative would be to grab the Agent ID from the output
    # instead of the Agent name, and query Wazuh again to an URL like
    #  url = f"{self.WAZUH_HOST}/agents/<Agent ID>/config/agent/labels"
    # that retrieves the labels information for the Agent, which includes
    # the exact OpenStack Server UUID
    uuid_re = re.compile(
        r"([0-9a-fA-F]{8}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{12})$"
    )
    server_id_l = []
    for server in data:
        name = server["name"]
        match = uuid_re.search(name)
        if match:
            server_id = match.group(1)
            server_id_l.append(server_id)
        else:
            logger.error("failed to extract Server ID from %s", server)

    logger.info("returning a list of %s Server IDs", len(server_id_l))
    return server_id_l
