---
name: "alert.flavor.properties.mismatch"
pack: "stackstorm_openstack"
description: "Sends Jira Ticket when it finds a Flavor mismatch is found between the source and target clouds"
enabled: true

trigger:
  type: "stackstorm_openstack.flavor.flavor_mismatch"

action:
  ref: "jira.create_issue"
  parameters:
    summary: "[Stackstorm Alert]: Flavor mismatch detected - {{trigger.flavor_name}}"
    type: Task
    description: >
      Details:\\
      - Flavor Name: {{trigger.flavor_name}}\\
      - Sync Direction: {{trigger.source_cloud}} {{ '>>>' }} {{trigger.target_cloud}}\\
      - Source Flavor ID: {{trigger.source_flavor_id}}\\
      - Target Flavor ID: {{trigger.target_flavor_id}}\\
      \\
      Mismatch:\\
      {{trigger.flavor_mismatch}}\\
      \\
      Source Flavor Properties:\\
      {{trigger.source_flavor_properties}}\\
      \\
      Target Flavor Properties:\\
      {{trigger.target_flavor_properties}}\\
