---
name: "alert.image.metadata.mismatch"
pack: "stackstorm_openstack"
description: "Sends Jira Ticket for Image metadata mismatch between source and target cloud"
enabled: true

trigger:
  type: "stackstorm_openstack.image.metadata_mismatch"

action:
  ref: "jira.create_issue"
  parameters:
    summary: "[Stackstorm Alert]: Image metadata mismatch between source and target cloud"
    type: Problem
    description: >
      Image metadata mismatch Details:\\
      - Name: {{trigger.image_name}}\\
      - Source Metadata: {{trigger.source_metadata}}\\
      - Target Cloud: {{trigger.target_cloud}}\\
