---
name: chatops.pr.reminder.personal
pack: stackstorm_openstack
description: Send a personal reminder request every Monday at 9AM to the ChatOps application
enabled: true

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: "Europe/London"
    day_of_week: mon
    hour: 9
    minute: 00


action:
  ref: stackstorm_openstack.chatops.pr_reminder
  parameters:
    chatops_reminder_type: "personal"
