---
name: "hv.compute.service.disable"
pack: "stackstorm_openstack"
description: "Triggers the disable action when the hypervisor state changes from 'RUNNING' to 'PENDING MAINTENANCE'"
enabled: true
criteria:
  trigger.previous_state:
    type: inside
    pattern: ["RUNNING", "EMPTY"]
  trigger.current_state:
    type: equals
    pattern: PENDING_MAINTENANCE
  trigger.hypervisor_name:
    type: inside
    pattern:
      - "hv742.nubes.rl.ac.uk"
      - "hv741.nubes.rl.ac.uk"
      - "hv713.nubes.rl.ac.uk"
      - "hv740.nubes.rl.ac.uk"
      - "hv686.nubes.rl.ac.uk"
      - "hv646.nubes.rl.ac.uk"

trigger:
  type: "stackstorm_openstack.hypervisor.state_change"

action:
  ref: "stackstorm_openstack.hv.compute.service.disable"
  parameters:
    cloud_account: "dev"
    hypervisor_name: "{{ trigger.hypervisor_name }}"
    disabled_reason: "Stackstorm: Disabled for Maintenance"
