---
name: "hv.drain.for.maintenance"
pack: "stackstorm_openstack"
description: "Drains a hypervisor for patching"
enabled: false

criteria:
  trigger.action:
    type: equals
    pattern: DRAIN

trigger:
  type: "stackstorm_openstack.hypervisor.state_change"

action:
  ref: "stackstorm_openstack.hypervisor.drain"
  parameters:
    hypervisor_name: "{{ trigger.hypervisor_name }}"
    cloud_account: "{{ trigger.cloud_account }}"
    disabled_reason: "Stackstorm: Draining"
