---
name: "hv.maintenance.notification"
pack: "stackstorm_openstack"
description: "Sends a notification to users when hypervisor is set to drain"
enabled: true

criteria:
  trigger.previous_state:
    type: inside
    pattern: [null, PENDING_MAINTENANCE]
  trigger.current_state:
    type: equals
    pattern: DRAINING

trigger:
  type: "stackstorm_openstack.hypervisor.state_change"

action:
  ref: "stackstorm_openstack.email.users.with.vms.on.hv.maintenance.notification"
  parameters:
    hypervisor_name: "{{ trigger.hypervisor_name }}"
    cloud_account: "dev"
    send_email: false
    webhook: "server-migrate"
