---
name: "hv.post.reboot"
pack: "stackstorm_openstack"
description: "Removes the scheduled downtime, removes the alertmanager silence and enables the hv in openstack when the hv is back up."
enabled: true

criteria:
  trigger.previous_state:
    type: regex
    pattern: (DOWN|DRAINED)
  trigger.current_state:
    type: equals
    pattern: REBOOTED

trigger:
  type: "stackstorm_openstack.hypervisor.state_change"

action:
  ref: "stackstorm_openstack.hv.post.reboot"
  parameters:
    alertmanager_account_name: "default"
    icinga_account_name: "default"
    name: "{{ trigger.hypervisor_name }}"
    cloud_account: "dev"
