---
name: "hv.patch.reboot"
pack: "stackstorm_openstack"
description: "Starts the patch action on a host"
enabled: true
criteria:
  trigger.action:
    type: equals
    pattern: PATCH
trigger:
  type: "stackstorm_openstack.hypervisor.state_change"
action:
  ref: "stackstorm_openstack.hypervisor.patch"
  parameters:
    hypervisor_hostname: "{{ trigger.hypervisor_name }}"
    cloud_account: "{{ trigger.cloud_account }}"
