---
name: "jira.request.create.project"
pack: "stackstorm_openstack"
description: "Handles JIRA issues requesting OpenStack project creation."
enabled: true

trigger:
  type: "stackstorm_openstack.jira.request.create.project"

action:
  ref: "stackstorm_openstack.jira.request.create.project"
  parameters:
    issue_key : "{{ trigger.issue_key }}"
