---
name: "webhook.server.migrate"
pack: "stackstorm_openstack"
description: "Uses the webhook to live migrate the server."
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "server-migrate"

criteria:
  # Whitelist for groups of flavors
  # e.g. pattern (^l3.*)|(^l2.*) allows migraion of l3 and l2 flavors
  trigger.body.flavor_id#1:
    type: regex
    pattern: (^l3.*)|(^l2.*)

  # Blacklist specific flavors from migration
  # e.g. pattern ["l2.tiny", "l3.large"] will prevent migrations of those flavors
  # specifically but not all l2 and l3 flavors. Flavors here can still be migrated
  # manually using the stackstorm_openstack.server.migrate action
  trigger.body.flavor_id#2:
    type: ninside
    pattern: ["m1.tiny"]

action:
  ref: "stackstorm_openstack.server.migrate"
  parameters:
    server_id: "{{ trigger.body.server_id }}"
    snapshot: "{{ 'true' if not trigger.body.server_name.startswith('amphora-') else 'false' }}"
