---
name: "webhook.server.migrate"
pack: "stackstorm_openstack"
description: "Uses the webhook to live migrate the server."
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "migrate-server"

criteria:
  trigger.body.flavor_id:
    type: regex
    pattern: (^l3.*)|(^l2.*)

action:
  ref: "stackstorm_openstack.server.migrate"
  parameters:
    server_id: "{{ trigger.body.server_id }}"
    server_status: "{{ trigger.body.server_status }}"
    flavor_id: "{{ trigger.body.flavor_id }}"
