name: Staging into main

on:
  pull_request:
    branches:
      - "main"

jobs:
  check_staging_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source is staging
        if: github.head_ref != 'staging' && github.head_ref != 'prod-promotion'
        run: exit 1
